language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_TOKEN
    - secure: XPvxe+LEp8pZ2cW42CqQv6MVavNw5weT+o5VtaevTd6koZ9rc77NSNpkCwAYa6nYTlAmRmxRCo3RNG/3yG50ZIUVzysbVXKmnN+t1c61vggV3RkL4FOpQoL5to14RiPrrZdDuWNEwaS8I/2UaCBPxF7Lw6LIQeGdv2SojCXF3gP21hJGujkqaWx6tlBEfxKj8SOjcEEM9waVBIQYdKxAdJD0nH7pEwpMNDNvVWuOIxHvWk6XauA4HQ252BQmurLRufTzZyOZCJwaBqlPbLcW9DYPz0IR/GtvNUXLqHzrrlwURNreDSvIOCkf7XsJcXE9Oz6l1S+tU4B6bMbIHXmOJRm8qIZQiRkxw/ZPBeXWOBvXWJv2TFzxHbqZkAbkEi8+XyeQcKKKFsN4W+eKaBe3PIBrN4VqkopZrLH6axxBm3SJ8y7mlwhggDC1d1xEs0IB5SoMKa7h+yQsJLNtt02HsHejVsBnUpp4AanwfiM/KKbgVrrzPZ3WwggoVttV2SH4JMJGw+lHWp6yMRTyWX5U5UNwMwDSEhtViEBFqb+Ae0t4qfTRiPnaUq5b4udkoDu6HLYYt+qAsUARep8MenAD0m1ZrEGMIgkjbA74+LdhIoOJtYNSMNH/GqOvR8O/G9qgDGaHkkueoMfE/gGsXy7PkTzIVvEHsMCV3eWwmxBU0Tw=
    # FIREBASE_SECRET
    - secure: Rx/hnJaWqy16bwgoTv5Ye6mkdqhTvmedO9wOqIqXUtTM7KeuAAcqR88/S4gbQoik2q/QgmxJUcExTooFJDtq1YSsJgMXb593iVIRmIghyX6ukGt+jVYCZjvoN+I5RKxxSMoIBT/hvzdcsBJQoYDFz/HII2y/fFRqs6/AbTRQ23UqBpYWO3AEi9AyLRjfogQ74cCEgFE0z5pE7ecoxjWYMIfw6U9r9OskmLOx0F8BXDHyRFr0pooqSHA0Y7eBSpZlVb4h3wWb5AUd0Ln8VdV8/pqbcxYJ2bHzwHDa9aRkh2HWFwRJODG/3DCb89j6tUAwiGrjWujoV2fqYB4jWNv2UPn8TeLA8llKCxQwQIRi29jJ2io4hH9ovhlisJjIV9cdw0/+YN/WkH0KqWNN4NGHles65fYCLJFxjgA1n0drE/Gc7p8N3fshd6WlxYh1jbR4Dz3mrt2pLODsPJrbdWinAaUMN7mYp/VRHqlClm1qIFnqvHd0VArj6iVuA1nuDD5IAELoKo4ds9AokSHlNdZfr+YLnxmlK+Cne5xjdFGuCsNLSTPIY/tfhUif/fHFr9/KgEu1ibXkAxQPrwcvekBoMYx6d2IdzcbD9doVCRg2wGrvw5aOf00CgFulfGBVITVqpiLtWgxcXYpAyAZa8rhiQeKuVi+LY7XKN2a42JY7x4Y=
